name: 🚀 Build APK Android

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-android:
    name: Build APK (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm install --global eas-cli
      - run: eas whoami
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      - run: eas build --platform android --profile preview --non-interactive --no-wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          EAS_NO_VCS: 1
